### ISSUE TITLE
Remove blinking cursor for <code>

### ISSUE THREAD

**Issue by hftf** [nmartin84/logseq-tokyo-night-theme#3]
Thanks for the theme! In my opinion, there is no necessity for inline code elements to display a fake blinking cursor. The animation provides no actual function. Furthermore, it is not vertically center aligned on my end.

In fact, I use inline code most frequently not to represent code or text specifically to be entered at all, but for the element's other properties (monospace font) and visual distinctiveness. Sometimes, I even use `|` to represent an actual cursor in an example of a keyboard user interaction, which conflicts with the unwanted cursor. See an example of this below:

<img width="806" alt="Screen Shot 2021-09-15 at 16 06 50" src="https://user-images.githubusercontent.com/312957/133502194-43989375-fa77-4c63-8f47-53463c43d727.png">

Re: https://github.com/nmartin84/logseq-tokyo-night-theme/blob/fcc122b4695955012411f3d9eb2f7ee14aa2098d/tokyo.css#L564-L575

**Comment by nmartin84** [comment]
Thanks for the feedback! Yeah I wasn't real sure if a blinking cursor would be a good thing or not, I think it would be better to remove it by default and leave it as a optional piece the user can add. I will update this shortly!
